"use client";

import { useState, useEffect, useRef } from "react";
import Link from "next/link";

interface GeneratedDoc {
  topic: string;
  content: string;
  generatedAt: string;
}

interface AIContentClientProps {
  userId: string;
  userRole: string;
}

export default function AIContentClient({ userRole }: AIContentClientProps) {
  const [topic, setTopic] = useState("");
  const [generating, setGenerating] = useState(false);
  const [documents, setDocuments] = useState<GeneratedDoc[]>([]);
  const [remaining, setRemaining] = useState<number | null>(null);
  const [isFounder, setIsFounder] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeDoc, setActiveDoc] = useState<GeneratedDoc | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const DAILY_LIMIT = 3;

  // Fetch remaining quota on load
  useEffect(() => {
    fetch("/api/ai/generate")
      .then((r) => r.json())
      .then((d) => {
        setRemaining(d.remaining ?? null);
        setIsFounder(d.isFounder ?? false);
      })
      .catch(() => {});
  }, []);

  async function generate() {
    const trimmed = topic.trim();
    if (!trimmed || generating) return;
    setGenerating(true);
    setError(null);

    try {
      const res = await fetch("/api/ai/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic: trimmed }),
      });
      const data = await res.json();

      if (!res.ok) {
        setError(data.error ?? "Generation failed.");
        return;
      }

      const doc: GeneratedDoc = {
        topic: data.topic,
        content: data.content,
        generatedAt: data.generatedAt,
      };

      setDocuments((prev) => [doc, ...prev]);
      setActiveDoc(doc);
      setTopic("");
      if (data.remaining !== undefined && data.remaining !== null) {
        setRemaining(data.remaining);
      }
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setGenerating(false);
    }
  }

  function handlePrint() {
    if (!activeDoc) return;
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${activeDoc.topic} – ExamArchive AI</title>
  <style>
    body { font-family: Georgia, serif; max-width: 720px; margin: 2rem auto; color: #1a1a1a; line-height: 1.7; }
    h1 { color: #D3273E; border-bottom: 2px solid #D3273E; padding-bottom: 0.5rem; }
    h2 { color: #003B49; margin-top: 1.5rem; }
    h3 { color: #003B49; }
    p, li { font-size: 0.95rem; }
    .meta { color: #666; font-size: 0.8rem; margin-bottom: 1.5rem; }
    @media print { body { margin: 1cm; } }
  </style>
</head>
<body>
  <h1>${activeDoc.topic}</h1>
  <p class="meta">Generated by ExamArchive AI · ${new Date(activeDoc.generatedAt).toLocaleString()}</p>
  <div>${markdownToHtml(activeDoc.content)}</div>
</body>
</html>`);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  }

  function markdownToHtml(md: string): string {
    return md
      .replace(/^## (.+)$/gm, "<h2>$1</h2>")
      .replace(/^### (.+)$/gm, "<h3>$1</h3>")
      .replace(/^- (.+)$/gm, "<li>$1</li>")
      .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\n\n/g, "</p><p>")
      .replace(/^(?!<[hul])(.+)$/gm, "<p>$1</p>");
  }

  const canGenerate = isFounder || (remaining !== null && remaining > 0);

  return (
    <div style={{ maxWidth: 800, margin: "0 auto", padding: "1.5rem 1rem" }}>
      {/* Header */}
      <div style={{ marginBottom: "1.5rem" }}>
        <h1
          style={{
            fontSize: "1.6rem",
            fontWeight: 800,
            color: "var(--color-text)",
            margin: 0,
            display: "flex",
            alignItems: "center",
            gap: "0.5rem",
          }}
        >
          <span>✨</span> AI Generated Content
        </h1>
        <p style={{ color: "var(--color-text-muted)", marginTop: "0.35rem", fontSize: "0.9rem" }}>
          Generate AI-powered study summaries and exam revision documents. ExamBot uses Gemini
          to produce structured revision notes tailored to your topic.
        </p>
      </div>

      {/* Quota badge */}
      <div
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: "0.4rem",
          padding: "0.35rem 0.75rem",
          borderRadius: 9999,
          background: isFounder
            ? "linear-gradient(135deg, #7c3aed, #4f46e5)"
            : remaining === 0
            ? "#fce8eb"
            : "var(--color-accent-soft)",
          color: isFounder ? "#fff" : remaining === 0 ? "var(--brand-crimson)" : "var(--color-text)",
          fontSize: "0.8rem",
          fontWeight: 600,
          marginBottom: "1.25rem",
        }}
      >
        {isFounder ? (
          <>👑 Founder – Unlimited generations</>
        ) : remaining === null ? (
          <>⏳ Loading quota…</>
        ) : (
          <>
            📄 {remaining}/{DAILY_LIMIT} generations remaining today
          </>
        )}
      </div>

      {/* Generator card */}
      <div
        style={{
          background: "var(--color-surface)",
          border: "1px solid var(--color-border)",
          borderRadius: "var(--radius-lg)",
          padding: "1.25rem",
          marginBottom: "1.5rem",
        }}
      >
        <label
          htmlFor="ai-topic"
          style={{ fontWeight: 600, fontSize: "0.875rem", display: "block", marginBottom: "0.5rem" }}
        >
          What topic should ExamBot summarise?
        </label>
        <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
          <input
            id="ai-topic"
            type="text"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && canGenerate && generate()}
            placeholder="e.g. Thermodynamics, Indian Constitution, Cell Biology…"
            maxLength={500}
            disabled={generating || !canGenerate}
            className="input-field"
            style={{ flex: 1, minWidth: 200 }}
          />
          <button
            onClick={generate}
            disabled={generating || !topic.trim() || !canGenerate}
            className="btn-primary"
            style={{ whiteSpace: "nowrap" }}
          >
            {generating ? "Generating…" : "✨ Generate"}
          </button>
        </div>

        {!canGenerate && !isFounder && (
          <p style={{ marginTop: "0.6rem", fontSize: "0.8rem", color: "var(--brand-crimson)" }}>
            Daily limit reached. Come back tomorrow for {DAILY_LIMIT} more generations.
          </p>
        )}

        {error && (
          <p style={{ marginTop: "0.6rem", fontSize: "0.8rem", color: "var(--brand-crimson)" }}>
            ⚠ {error}
          </p>
        )}

        {/* Quick topic suggestions */}
        <div style={{ marginTop: "0.75rem", display: "flex", flexWrap: "wrap", gap: "0.4rem" }}>
          {["Photosynthesis", "Ohm's Law", "Federalism", "Organic Chemistry Basics", "Newton's Laws"].map(
            (s) => (
              <button
                key={s}
                onClick={() => setTopic(s)}
                disabled={generating || !canGenerate}
                style={{
                  padding: "0.2rem 0.6rem",
                  fontSize: "0.75rem",
                  borderRadius: 9999,
                  border: "1px solid var(--color-border)",
                  background: "transparent",
                  cursor: generating || !canGenerate ? "not-allowed" : "pointer",
                  color: "var(--color-text-muted)",
                  transition: "border-color 0.15s",
                }}
              >
                {s}
              </button>
            ),
          )}
        </div>
      </div>

      {/* Generated documents list + viewer */}
      {documents.length > 0 && (
        <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: "1rem" }}>
          {/* Viewer */}
          {activeDoc && (
            <div
              style={{
                background: "var(--color-surface)",
                border: "1px solid var(--color-border)",
                borderRadius: "var(--radius-lg)",
                padding: "1.25rem",
                position: "relative",
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "flex-start",
                  marginBottom: "1rem",
                  gap: "0.5rem",
                  flexWrap: "wrap",
                }}
              >
                <div>
                  <h2 style={{ margin: 0, fontSize: "1.1rem", fontWeight: 700 }}>
                    {activeDoc.topic}
                  </h2>
                  <p style={{ margin: 0, fontSize: "0.75rem", color: "var(--color-text-muted)" }}>
                    Generated {new Date(activeDoc.generatedAt).toLocaleString()}
                  </p>
                </div>
                <button
                  onClick={handlePrint}
                  className="btn"
                  style={{ fontSize: "0.8rem", whiteSpace: "nowrap" }}
                >
                  🖨️ Print / Save PDF
                </button>
              </div>

              <div
                ref={printRef}
                style={{
                  fontSize: "0.875rem",
                  lineHeight: 1.7,
                  color: "var(--color-text)",
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-word",
                }}
              >
                {activeDoc.content}
              </div>
            </div>
          )}

          {/* Document history (if more than 1) */}
          {documents.length > 1 && (
            <div>
              <p style={{ fontWeight: 600, fontSize: "0.8rem", color: "var(--color-text-muted)", marginBottom: "0.5rem" }}>
                Session history
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: "0.4rem" }}>
                {documents.map((doc, i) => (
                  <button
                    key={i}
                    onClick={() => setActiveDoc(doc)}
                    style={{
                      textAlign: "left",
                      padding: "0.5rem 0.75rem",
                      borderRadius: "var(--radius-sm)",
                      border: `1px solid ${activeDoc === doc ? "var(--brand-crimson)" : "var(--color-border)"}`,
                      background: activeDoc === doc ? "var(--color-accent-soft)" : "var(--color-surface)",
                      cursor: "pointer",
                      fontSize: "0.8rem",
                      color: "var(--color-text)",
                    }}
                  >
                    <strong>{doc.topic}</strong>
                    <span style={{ color: "var(--color-text-muted)", marginLeft: "0.5rem" }}>
                      {new Date(doc.generatedAt).toLocaleTimeString()}
                    </span>
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Empty state */}
      {documents.length === 0 && !generating && (
        <div
          style={{
            textAlign: "center",
            padding: "3rem 1rem",
            color: "var(--color-text-muted)",
          }}
        >
          <div style={{ fontSize: 48, marginBottom: "0.75rem" }}>✨</div>
          <p style={{ fontWeight: 600 }}>No documents generated yet</p>
          <p style={{ fontSize: "0.85rem" }}>
            Enter a topic above and click <em>Generate</em> to create your first AI study summary.
          </p>
        </div>
      )}

      {/* Info box */}
      <div
        style={{
          marginTop: "2rem",
          padding: "1rem",
          background: "var(--color-accent-soft)",
          borderRadius: "var(--radius-md)",
          fontSize: "0.8rem",
          color: "var(--color-text-muted)",
          lineHeight: 1.6,
        }}
      >
        <strong style={{ color: "var(--color-text)" }}>ℹ How it works:</strong>{" "}
        ExamBot uses Google Gemini to generate a structured revision document for your topic.
        Use the <em>Print / Save PDF</em> button to save the document. Generated content is for study
        reference only — always verify with official sources.{" "}
        {userRole !== "founder" && (
          <>
            You have a daily limit of <strong>{DAILY_LIMIT} documents</strong>. Need more? Browse
            real papers at <Link href="/browse" style={{ color: "var(--brand-crimson)" }}>/browse</Link>.
          </>
        )}
      </div>
    </div>
  );
}
